name: CDCI

on:
  push:
    branches:
      - deploy-to-ec2

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout The Sourcecode
        uses: actions/checkout@v3

      - name: Login to Docker Hub
        run: docker login -u ${{ secrets.DOCKERHUB_USERNAME }} -p ${{ secrets.DOCKERHUB_PASSWORD }}

      - name: Build Docker image
        run: docker build --target build -t ${{ secrets.DOCKERHUB_USERNAME }}/cicd-ec2 .

      - name: Publish image to DockerHub
        run: docker push ${{ secrets.DOCKERHUB_USERNAME }}/cicd-ec2:latest

  deploy:
    needs: build
    runs-on: aws-ec2
    steps:
      - name: Pull Image from DockerHub
        run: docker pull ${{ secrets.DOCKERHUB_USERNAME }}/cicd-ec2:latest
      - name: Delete the Old Container
        run: docker rm -f reactContainer
      - name: Run Docker Container
        run: docker run -d -p 5173:80 --name reactContainer ${{ secrets.DOCKERHUB_USERNAME }}/cicd-ec2
