name:CDCI

on:
  push:
    branches
      - deploy-to-ec2

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout The Sourcecode
        uses: actions/checkout@v3

      - name: Login to Docker Hub
        run: docker login -u ${{ secrets.DOCKERHUB_USERNAME }} -p ${{ secrets.DOCKERHUB_PASSWORD }}

      - name: Build Docker image
        run: docker build --target build -t ${{ secrets.DOCKERHUB_USERNAME }}/cicd-ec2 .

      - name: Publish image to DockerHub
        run: docker push ${{ secrets.DOCKERHUB_USERNAME }}/cicd-ec2:latest

